github/include-fragment-element

include-fragment-element.js
test/test.js

This branch allows the `src` attribute to be assigned after the `include-fragment` element has been attached to the page.
The page is loaded with the following markup:
```html
<include-fragment src="">
Loading...
</include-fragment>
```
JavaScript later assigns the `src` attribute so that the replacement content is then fetched and swapped into the page.
```js
document.querySelector('include-fragment').src = '/test'
```
The current behavior considers the lack of a `src` value to be an unrecoverable failure. Setting `src` after the element has been attached *does* fetch the new content, but it's never inserted into the page.
/cc @josh

Fix post-attach src attribute assignment

---

include-fragment-element.js

Following up to #18, this suppresses the "uncaught missing src" promise message in the Chrome web inspector on page load. It just needs some `catch` handler registered to make Chrome happy.
An alternative would be to avoid loading the `data` promise in the `createdCallback` if `this.src` is null. That would result in `element.data` returning null immediately after creating the element via JS.
/cc @josh

Suppress error message in web console during pre-load.

---

include-fragment-element.css

I wanted to include the `include-fragment-element.css` with this package. The css exists to normalize the custom html elements.
Then in app we're going to include this css with
```scss
@import "include-fragment-element/include-fragment-element";
```
to: @github/js 
cc: @github/design-systems

Adding include-fragment-element.css to include with package

---

README.md

In the example, the `.tips` div will still be there, just with its contents swapped out.

Clarify example

---

bower.json

I ran into an issue where my [Dependency CI](https://dependencyci.com/github/education/classroom/builds/77) was failing because npm couldn't find the license.
This adds the `LICENSE` to the `bower.json` so that npm can pick it up.
I'm pretty sure this solves the issue but I'm not 100% sure ¯\_(ツ)_/¯

Add LICENSE to bower.json

---

bower.json
include-fragment-element.js
test/test.html
test/test.js

Currently if the `data` promise resolves while the element does not have a parent, the following error will be logged:
```
Uncaught (in promise) DOMException: Failed to execute 'insertAdjacentHTML' on 'Element': The element has no parent.
at http://localhost:5001/include-fragment-element.js:16:10
at <anonymous>
```
This pull request guards for this case and also makes a few small tweaks to get the tests running again.
I was getting the following error on master from bower because of a missing `es5-basic-shim`:
```
bower es5-basic-shim#1.0.6     ECMDERR Failed to execute "git ls-remote --tags --heads https://github.com/radubrehar/es5-basic-shim.git", exit code of #128
```
Also removes a few linter errors that exist on master.

Guard against missing parent when replacing

---

include-fragment-element.js
package-lock.json
package.json
test/test.js

~when the lazyload prop is set it will defer loading until the get()
function is called. This will allow lazy loading to be called by what
means needed. This will allow this component to remain simple and prefer
composition to bloat.~
- removed the getdata call in the constructor ~to allow for lazyloading
the data~.
- moved the getdata call into the handledata function to consolidate the
calls and make the function a little simpler.
- removed self = this to make the load function simpler
- fixed the tests to run async and cleared DOM after each test.
- ticked the version number to a ~minor~ patch update.

Fixed tests and a few changes:

---

.babelrc
package.json

This PR means the build step now outputs a `dist/index-es.js` which keeps the ES6 export syntax, while still transpiling the rest of the code to ES5. This is useful for tools like Rollup.

feat: output ES module build for tools like Rollup

---

include-fragment-element.js

`Document.createEvent` and `Event.initEvent` are deprecated. This patch replaces those with a simple `new Event(name)` construction instead.
I think creating the event from `target.ownerDocument` doesn't matter? I couldn't find any reference to it on MDN or when googling it. Please let me know if you think it matters and in which way and I can test for it 🔍 
- [`Document.createEvent()` - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/createEvent)
- [`Event.initEvent()` - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Event/initEvent)
- [`Event()` - MDN](https://developer.mozilla.org/en-US/docs/Web/API/Event/Event)

use `Event` constructor instead of `event.initEvent`

---

index.d.ts

The TypeScript definition is incomplete as it doesn't properly reflect this code:
https://github.com/github/include-fragment-element/blob/213d197be7a34d01de29e28cfbd25ca28e8b5522/include-fragment-element.js#L143-L146
This PR adds the declaration of `IncludeFragmentElement` to the global window object, as that mutation is happening within the code and so should be reflected in the types.
This type is already in the FlowType code, somewhat implicitly by having `declare class` _outside_ of `declare module`:
https://github.com/github/include-fragment-element/blob/213d197be7a34d01de29e28cfbd25ca28e8b5522/include-fragment-element.js.flow#L3

types(TS): add window declaration

---

include-fragment-element.js.flow

Fixes an error importing the class.
```js
import IncludeFragmentElement from '@github/include-fragment-element'
```
> Error: Importing from an untyped module makes it `any` and is not safe!

Include module in Flow declaration

---

include-fragment-element.js
include-fragment-element.js.flow
index.d.ts
test/test.js

This is to support `github/github`'s content type for HTML fragment (`text/html; fragment`) so we can move away from XHR checks with a clear path forward.  
I've also added a special case for `accept="*/*"` in 6dc78672649e1cba77c1d3e198316c323ecd125c which I'm 😓 not too sure about.

Allow setting custom Accept header for requests

---

.github/workflows/test.yml

Created via Actions' official [starter-workflows](https://github.com/actions/starter-workflows).
Log: https://github.com/github/include-fragment-element/runs/289666819#step:4:55
I wanted to set this up because one day Travis CI's open source queue was frustratingly long.

Set up CI with GitHub Actions

---

package-lock.json
package.json
test/karma.config.js

We can add https://github.com/koddsson/karma-edgium-launcher to the list when https://github.com/actions/virtual-environments/issues/99 is resolved.
(We could run https://github.com/karma-runner/karma-edge-launcher on Windows machines but I'd rather wait for Edgium on all platforms)
Motivated by https://github.com/github/include-fragment-element/pull/52#discussion_r346848398.

Also run tests in firefox

---

include-fragment-element.js
test/test.js

I might be doing regex wrong but as far as I can tell, when we add a `+` to the accept header everything goes to hell.
I couldn't get anything to match correctly:
```
> 'text/fragment+html'.match('text/fragment+html')
null
> 'text/fragment\+html'.match('text/fragment+html')
null
> 'text/fragment\+html'.match('text/fragment\+html')
null
> 'text/fragment\+html'.match('text/fragment+html')
null
> 'text/fragment+html'.match('text/fragment\+html')
null
```
But using a simple string includes works fine 😄 
```
> 'text/fragment+html'.includes('text/fragment+html')
true
```
We use a `.includes(..)`  here since the content type might have additional info such as charset. Something like `text/fragment+html; charset=utf8`.

Fix checking of accept header

---

README.md
src/index.ts
test/test.js

- Replace `el.insertAdjacentHTML` + `parent.removeChild(el)` with `el.replaceWith`.
- Add custom events to provide fragment access
This is to support our use cases for in-place refreshing of the same fragment. In those cases, the source will return another instance of `include-fragment` to be loaded on demand. We use these events to:
1. Obtain a reference of a focus target so we can restore focus after node replacement
2. Manipulate the fragment to restore element expand states prior to node replacement
3. Check if user is currently interacting with the element to prevent disruptive updates

Add custom events to provide fragment access

---

src/index.ts

`isConnected` is a property of the `Node` interface returning a boolean indicating whether the node is connected. It is effectively the same as `_attached`, making `_attached` redundant.

refactor: change `_attached` to `isConnected`

---

README.md
examples/index.html
src/index.ts
test/test.js

This adds a new attribute `loading`, which can be either `lazy` or `eager` (the default value). This follows similar semantics & behaviour to [the loading attribute of `<img>` tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Img#attr-loading). 
If the `loading` value is set to _anything but_ `lazy` then the existing behaviour applies - therefore this is not a breaking change.
If the `loading` value is set to `lazy` then the fetch will not trigger as part of the `connectedCallback`. Instead the element is added to a global `IntersectionObserver`, and only when the element is close to being visible in the viewport will the contents be fetched and the element replaced.
Currently the threshold is set to `256px` from the bottom of the viewport with a threshold of `0.1`. These …

Feat add loading lazy

---

src/index.ts
test/test.js

Fixes #21
This refactors `fire` to return a Promise, so that we can determine when an event has been fired (as we're not firing event synchronously).
The test is pretty contrived and implementation dependant, but it red-greens consistently and race condition tests are hard to otherwise verify :shrug:

fix: guarantee order of load events

---

src/index.ts
test/test.js

_Fixes https://github.com/github/include-fragment-element/issues/67_
This PR fixes https://github.com/github/include-fragment-element/issues/67 where calling `load()` on a `loading=lazy` element causes the contents not to be replaced when the element becomes visible.
There are two bugs at play here:
1. We were calling `observer.unobserve` when `load()` was called. This is incorrect as it should only be called once content replacement has happened.
2. `load()` doesn't actually properly preload the request, since nothing is done with the response - it should be saved into the weakmap but that is only done by `getData()` not `load()`. 
The fix here is twofold:
1. Remove the `observer.unobserve` call from the `load()` code.
2. Move `load()` logic to a private function and instead call …

Fix bug where calling load() on lazy element breaks the loading

---

README.md

Hi, I think this line is a mistake and should be removed to avoid confusion.

Remove a redundant line

---

src/index.ts

In a future pull request, I want to check the internal state of the component in one of these functions but in order to do that, I'd have to expose the property on the component API. This is undesirable since whenever we want to change the internal functionality we have to make a breaking change release. As the functionality grows this becomes more and more unwieldy.
Instead of doing all that, I want to move these essentially private functions into the component so that we can check the internal state of the component in these functions in the future.

Refactor private functions into the component

---

src/index.ts
test/test.js

Make sure not to fire off additional requests if there's already one in-flight. I chose to reflect this on the element through the read-only `busy` attribute.
Fixes #75

Check if there's a network request already in flight

---

src/index.ts

This will make future PRs like https://github.com/github/include-fragment-element/pull/81 easier to author and review.
The functionality (and published build compat) should be exactly the same, so the existing tests should cover this change.

Switch Promise chaining to async-await syntax.

---

src/index.ts

I accidentally did not include enough code in the `try` clause in https://github.com/github/include-fragment-element/pull/82 . This PR fixes that.

Fix the location of `try` in new async code.

---

src/index.ts

`.#getData()` had the type `Promise<string>`, but this is inaccurate. It could also return:
1. `string`
2. `Error`
This all sort of stems from the `privateData` `Map`, which did not have template types.
This PR adds an `async` keyword to avoid the first case, and adds additional types for the second case. This has consequences across quite a few methods, so I've split the PR out from https://github.com/github/include-fragment-element/pull/81 for separate discussion.

Fix up types for cached and returned data.

---

package.json

I no longer use ESLint personally, so I rely on the commandline for formatting projects like this. A formatting command makes this easier.

Add a script for `npm run format`.

---

src/index.ts

@lgarron a slight change in the API to be more idiomatic (and also backwards compatible).
Instead of returning Error objects, we throw them so the Promise rejects.

throw errors rather than resolving them

---

src/index.ts
test/test.js

Closes https://github.com/github/include-fragment-element/issues/90 and https://github.com/github/include-fragment-element/issues/91
I'm adding a `refetch()` API that will clear the privateCache and fire the `src` request again.

add refetch API

---

.devcontainer/devcontainer.json
.github/workflows/nodejs.yml
.github/workflows/publish.yml

Node 22 will be active LTS by the end of the month, so the following changes have been made:
- Updated the development container to use Node 22
- Updated Actions to use Node 22
- Update Actions to publish with [provenance](https://docs.npmjs.com/generating-provenance-statements)

Upgrade node to 22 and add provenance

---

custom-elements.json
src/include-fragment-element.ts
test/test.js

Sending the actual error will help users understand why the fragment is failing

Send error information to event

---

src/include-fragment-element.ts
test/test.js

Part of https://github.com/github/primer/issues/5409
This moves the content type error check to before the `status !== 200` check. The content type one was never getting hit because it was passing `406` as a status code and getting caught by the not 200 check.

Refactor content type check for response handling
